name: Gen

on:
  push:
    branches:
      - main

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions
        with:
          uma: 50,10,-10,-30
          record: ./day
          outdir: ./record
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Gen Image
